### ISSUE TITLE
Add icon on map

### ISSUE THREAD

**Issue by yanickv** [mapzen/android#106]
Hi,

I would like to be able to add a custom icon on the map. The icon color needs to be changeable programatically (ex: not hardcoded in the yaml) and I need to be able to write a letter in the icon.

Is this possible? To do this do I also need to add something in Tangram-ES?

Here is an example:

![capture](https://cloud.githubusercontent.com/assets/3969320/15708958/f51a8a72-27cf-11e6-8540-f74adb1ec4c4.JPG)

Thanks,

Yanick

**Comment by ecgreb** [comment]
It is not yet possible to update icons programatically using the the Mapzen SDK API. However a possible solution might be using Tangram's API to modify the scene file at runtime.

https://github.com/tangrams/tangram-es/issues/650

It won't allow true dynamic loading of icons but you should be able to specify which icon will get used assuming all versions are available in your sprite sheet.

**Comment by tallytalwar** [comment]
One another way you can modify icons programmatically is to add a property and draw the icon based on that property.
For example, [here](https://github.com/tangrams/tangram-es/blob/076f32a6e638d061c52744aa949bae5d6eabd1dd/android/demo/src/com/mapzen/tangram/android/MainActivity.java#L140-L143), I am adding a color property to a custom point data and [here](https://github.com/tangrams/tangram-es/blob/076f32a6e638d061c52744aa949bae5d6eabd1dd/scenes/scene.yaml#L99) I am drawing the point using the color specified programmatically.

You can also do the same with sprite names, assuming you have the all the named sprites in the atlas.

**Comment by yanickv** [comment]
I added this to my yaml (which is based on Cinnabar):

    friend_locations:
        data: { source: friend_locations }
        point:
            filter: { type: point }
            draw:
                points:
                    sprite: castle
                    color: function () { return feature.color || 'black'; }
                    size: 35

And added this to my code:

                MapController controller = map.getMapController();
                MapData mapData = controller.addDataLayer("friend_locations");

                LngLat tappedPoint = new LngLat(-73.996142, 40.741050); 
                Map<String, String> props = new HashMap<>();
                props.put("type", "point");
                props.put("color", "#DFDF44");

                mapData.addPoint(tappedPoint, props);


And something fuzzy and yellow appeared on the map, but I expected a castle with a yellow background:

![screenshot_2016-06-01-23-35-54](https://cloud.githubusercontent.com/assets/3969320/15733336/f0c3c852-2852-11e6-80ad-623cc68b88af.png)

What am I doing wrong?

Thanks.

**Comment by tallytalwar** [comment]
Hey @yanickv 

The reason its not picking the `castle` sprite texture is because the `style` its requested to draw is a `points` style which is an in-build default style and does not refer to any texture sprites.
To have the icon texture show up with the appropriate background color, you have to make sure to use a style with the respective texture and sprite defined.

Example in the [cinnabar-style](https://github.com/tangrams/cinnabar-style/blob/gh-pages/cinnabar-style.yaml), there is a scene level [texture object](https://github.com/tangrams/cinnabar-style/blob/gh-pages/cinnabar-style.yaml#L237-L385) which defines the sprites. These texture is then used in an explicitly defined [icons style](https://github.com/tangrams/cinnabar-style/blob/gh-pages/cinnabar-style.yaml#L681-L685). Which is then used to [draw the icons](https://github.com/tangrams/cinnabar-style/blob/gh-pages/cinnabar-style.yaml#L5299-L5301). 

Now, when you use `color` property while drawing this `icons` style instead of `points` style, you should see appropriate sprite being drawn with that color as the background.

Hope this helps.

**Comment by yanickv** [comment]
Yeah! The castle icon is not showing and the color tint works well. But sometimes I see that the icon is underneath a street name, I guess there is some priority I have to tweak somewhere (with the bubble-wrap style for this test).

layers:
    friend_locations:
        data: { source: friend_locations }
        draw:
            icons:
                sprite: castle
                size: 18px
                interactive: true
                collide: false
                color: function () { return feature.color || 'black'; }
                priority: 1

Thanks a lot for your help!

Yanick

**Comment by tallytalwar** [comment]
Nice. Glad icon is showing up, with an appropriate tint.

To make sure icons are drawn above street names, you can use the `blend` and `blend_order` style properties.
Refer documentation for [blend](https://github.com/tangrams/tangram-docs/blob/b7a41c269a447f78314f4b61bb94a3d3a0f02667/pages/styles.md#blend) and [blend_order](https://github.com/tangrams/tangram-docs/blob/b7a41c269a447f78314f4b61bb94a3d3a0f02667/pages/styles.md#blend_order).

For an example you can refer bubble-wrap style for its usage: https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L744-L780

Another feature which we recently implemented in both tangram-js and tangram-es project is the unified rendering of icons/points with text. Refer https://github.com/tangrams/tangram-es/pull/721 and https://github.com/tangrams/tangram/pull/306 for some example usage. Note that this is available in latest tangram release, but not yet in mapzen android sdk. We are working on it to be available on mapzen android sdk soon.

**Comment by yanickv** [comment]
I tried the blend and blend_order and it works perfectly. Actually, tangrams/tangram#306 will probably do exactly what I want. To change the text I would use a function that would fetch the props set by the code.
