### ISSUE TITLE
Set tile API key in scene config and update stylesheets

### ISSUE THREAD

**Issue by matteblair** [mapzen/android#114]
It used to be that the only way to set a tile API key for tangram-es at runtime was to append it as a URL query to each tile request. This is no longer the case. In fact it is now preferred to set the API key for each data source as part of the scene configuration ([docs](https://mapzen.com/documentation/tangram/sources/#url_params)). As described in [this issue](https://github.com/tangrams/outdoor-style/issues/52#issuecomment-224087517), the append-directly-to-url method breaks down if, for example, vector tiles and terrain tiles require two different API keys. In our code, setting the key would look something like:

``` java
mapController.queueSceneUpdate("sources.osm.url_params", "{ api_key: ${MY_API_KEY} }");
mapController.applySceneUpdates();
```

**Comment by ecgreb** [comment]
Resurrecting this old issue for updating the way we set the API key for vector tile requests.

The [API key can now be set via a stylesheet global variable](https://github.com/tangrams/bubble-wrap/commit/6fd2e2433e6c3bce4db8ce75cfb3cad88b9a500e) which is sweet ... and stylesheet updates [can now be set when the scene is loaded](https://github.com/tangrams/tangram-es/pull/1173) to avoid re-parsing the scene file so let's do that :)

**Comment by tallytalwar** [comment]
Heads Up: With the newer releases of tangram android sdk, recommended way of applying these scene update will be along with the sceneLoad. (Refer: https://github.com/tangrams/tangram-es/pull/1173)

**Comment by ecgreb** [comment]
Bringing all the stylesheets up to date with latest release will also resolve missing marker styles in some of the bundled stylesheets that have become outdated such as Walkabout. (ex. https://github.com/mapzen/android/issues/216)
