### ISSUE TITLE
No map rendered on KitKat

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#115]
Note 3
Android 4.4.2
Tangram 0.2.2

Interesting that client data source (pins) are rendered but not the tiles themselves.

![image](https://cloud.githubusercontent.com/assets/464123/15869130/059a1bc2-2cb9-11e6-8d4d-efa42c07be59.png)

![image](https://cloud.githubusercontent.com/assets/464123/15869146/14dc27f6-2cb9-11e6-8530-b0bdcdc50780.png)

**Comment by ecgreb** [comment]
Reverting to Tangram 0.2.1 fixes the issue. cc @blair1618 @tallytalwar

**Comment by tallytalwar** [comment]
Any device logs available @ecgreb?

**Comment by ecgreb** [comment]
Trying to grab them now. Getting meaningful logs out of the Note 3 is a bit of a challenge ;)

**Comment by ecgreb** [comment]
This appears to be fixed in Tangram 0.3.1. But I am still seeing the other issue where the map renders but other UI elements vanish (menus, text, action bar, etc.) on KitKat.

Note 3/Android 4.4.2

I'll open another issue to track this.
