### ISSUE TITLE
Compass widget

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#116]
Add compass widget to current location layer similar to Eraser Map implementation.

**Comment by rwrx** [comment]
I have added compass from Eraser Map into Mapzen Android SDK in my local repository. Could I do push request? I tried to preserve your coding rules, but I am not sure if it really complains your coding rules. Also I have done two little changes in order to retain some compatibility with Google Maps.

**Comment by ecgreb** [comment]
Awesome! If you submit a pull request from your fork of the project all tests and code quality checks should run on Circle CI. You can also run them locally with `./gradlew clean verify`.

**Comment by rwrx** [comment]
Ok, but I didn't created tests to test compass. Should I create them to be pull request accepted? Also I have moved my location button to top left as it is in Google Maps and also made these buttons partly transparent as it is in Google Maps too. In the meantime I have added zoom buttons which were missing too. Is it ok to pull request all these things?

**Comment by ecgreb** [comment]
Submitting each feature in a separate pull request would be best. And yes any new classes/methods should have test coverage. If you run any issues with the tests we are here to help.

Porting the compass view from Eraser Map seems like a no brainer to include in the SDK. Other UI changes we would need to review once they are submitted so maybe let's start with the compass.

**Comment by rwrx** [comment]
I will try to separate each feature to own pull requests. Are tests mandatory in order to pull request? Because I don't have many time to create tests and also I didn't used tests before, so it will take me longer time to find out how to write tests.

**Comment by ecgreb** [comment]
We do require tests for all pull requests mainly for two reasons:

1. To help ensure the production code submitted works as expected since we don't have dedicated QA.
2. To safeguard against regressions when future changes are introduced that may impact your feature.

But like I said if you need help getting started with tests we are here to help. You can even feel free to create the pull request without tests and then based on that we can offer some guidance and suggestions.

Thanks again for taking the time to contribute!

**Comment by rwrx** [comment]
Hello. Finally I had some time to clean up code for Compass button and created pull request. I have also added two simple tests which I was able to somehow copy and edit from other tests. But I think that it will need more tests.

**Comment by sarahlensing** [comment]
This has been added to the sdk and will be available after https://github.com/mapzen/eraser-map/issues/816 is completed
