### ISSUE TITLE
Can't load map

### ISSUE THREAD

**Issue by iMakerkaushal** [mapzen/android#131]
cant load map in any of the page. i change the i created api key for both ans applied it as bellow

`
<string name="vector_tiles_key">vector-tiles-*****N</string>
<string name="turn_by_turn_key">valhalla-*****Y</string>
`

i also tried with only last 7 digits of my api key.

is it right way? in there anything else i should modify?

**Comment by sarahlensing** [comment]
You will need to use the entire api key, not just the last 7 digits

You might be missing submodules, did you run 
`git submodule init`
`git submodule update`
from the root directory?

Also what device and version of Android are you running?

**Comment by iMakerkaushal** [comment]
@sarahlensing thanks for the help, i'll try asap what you said. but one more thing before that, i need a complete document including these(git submodule init, git submodule update) commands. is it available anywhere?
