### ISSUE TITLE
Que: offline tile data in Android

### ISSUE THREAD

**Issue by iMakerkaushal** [mapzen/android#138]
Is it possible to **download tile data in android** device and then use it? i want to **download data of the netherlands**, is it available for download somewhere?

**Comment by blair1618** [comment]
Hello! Yes, it should be possible to download tile data to your device and use it offline. 

`MapzenMap` is built on top of the `MapController` class from [tangram-es](https://github.com/tangrams/tangram-es), which provides a way to override and redirect tile data requests. You can do this with a few steps: 
  1. Access the `MapController` for a `MapzenMap` through `MapzenMap$getMapController()`. 
  2. Create a custom [HttpHandler](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/HttpHandler.java) by overriding `HttpHandler$onRequest(String, Callback)` to fetch tiles from a local directory.
  3. Call `MapController$setHttpHandler(HttpHandler)` to give the map your custom handler. 

As for downloading all of the map tiles for a given area, I'll look into that and find out how to do that most conveniently.

**Comment by blair1618** [comment]
Ok, so I checked with our tiles team and we'll be working on a convenient "official" way to download tiles in bulk sometime in the next few months. For now, I threw together a python script that should get the job done: https://gist.github.com/blair1618/6bfb84d18df1088b907f0f0abf5ba6ca

Let us know if there's anything else we can help you with, or feel free to close the issue if your problem is solved!

**Comment by peterchaula** [comment]
I think we close this one off

**Comment by K-Leon** [comment]
I stumbled about this while chasing a similar issue - is there an example floating around or an official way to download data to an device?

**Comment by peterchaula** [comment]
@K-Leon I haven't seen one but it seems fairly easy to implement

**Comment by matteblair** [comment]
Oh that old gist link is broken - here's a working link to it: https://gist.github.com/matteblair/6bfb84d18df1088b907f0f0abf5ba6ca

A more convenient solution is still in the works, I promise!
