### ISSUE TITLE
Problem with git submodule update

### ISSUE THREAD

**Issue by rwrx** [mapzen/android#140]
When I run "git submodule update" in root directory of cloned repository I get this error:

![submodule_update](https://cloud.githubusercontent.com/assets/2378743/16541811/dad70e56-408e-11e6-88d6-7dc6a604478b.png)

I have runned "git submodule init" before calling update. Could you advise me what I should do to make it work?

Thank you.

**Comment by blair1618** [comment]
There are a few possible reasons your `clone` commands might be rejected, you can try some common fixes described here: https://help.github.com/articles/error-permission-denied-publickey/#platform-windows (I guessed from the screenshot that you are on Windows).

**Comment by rwrx** [comment]
Thank you. I realized that I didn't added public key to my GitHub account.
