### ISSUE TITLE
Group feature/component classes into separate packages

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#153]
To help keep things organized let's add a package for each major feature/component. Something like this:

`com.mapzen.android.graphics` - Tangram related classes
`com.mapzen.android.search` - Pelias related classes
`com.mapzen.android.routing` - Valhalla related classes
`com.mapzen.android.location` - LOST related classes

Common classes like API key related stuff, and dependency injection could remain in `com.mapzen.android` or we could create a `com.mapzen.android.core` package.

**Comment by sarahlensing** [comment]
This is complete
