### ISSUE TITLE
Walkabout style in SDK

### ISSUE THREAD

**Issue by rwrx** [mapzen/android#169]
When will be Walkabout style added officially to this Android SDK? I tried to add it as custom style to sample app and it worked well.

**Comment by ecgreb** [comment]
Yes. We are planning to make all of the official Mapzen styles available in the SDK.

**Comment by tallytalwar** [comment]
This One: https://github.com/tangrams/walkabout-style-more-labels

**Comment by rwrx** [comment]
Yes, that one I had in mind :).
