### ISSUE TITLE
Can we have a wiki of all the classes available in this SDK?

### ISSUE THREAD

**Issue by maheshgaya** [mapzen/android#175]
Can we have a developer guide Wiki for all the functions, and classes available for this SDK? Having a good documentation will help developers use this SDK more efficiently.

**Comment by ecgreb** [comment]
Agree. One option would be to publish the javadocs to github pages. Other options we should consider?

**Comment by maheshgaya** [comment]
That's a good one. We also need to have some type of version control, in case some of the functions get deprecated, or added, in a new version of the SDK.

**Comment by sarahlensing** [comment]
Javadocs published: http://mapzen.github.io/android/
Repo website updated: https://github.com/mapzen/android
