### ISSUE TITLE
Blue background in Walkabout style

### ISSUE THREAD

**Issue by rwrx** [mapzen/android#180]
I am not sure if I can post this issue here or rather to Tangram ES repository, but on my phone Huawei Y360-U61 with Android 4.2.2, API level 19 when I select Walkabout style in Style switcher activity in sample app it will show blue color instead of shaded roughness. Here is a screenshot:

![mapzen-walkabout](https://cloud.githubusercontent.com/assets/2378743/18818370/a23879c8-8377-11e6-943c-afa354d0e57b.jpg)

**Comment by blair1618** [comment]
That's fascinating! Are you able to get logs from your device with logcat?

**Comment by rwrx** [comment]
I created log file from logcat when this issue occurred (it is occurring always) and saved it here: https://gist.github.com/rwrx/98cf956c2f7cd24c4b995a1faa128fb6 .

**Comment by sarahlensing** [comment]
Closed due to inactivity, if this is still an issue please open a new ticket
