### ISSUE TITLE
Mapzen places API

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#184]
UI components that integrate search and visual map experience

* Place picker
* Place autocomplete
* Place details

**Comment by sarahlensing** [comment]
Closing in favor of more specific issues created after summary discussion:
https://github.com/mapzen/android/issues/193
https://github.com/mapzen/android/issues/194
https://github.com/mapzen/android/issues/195
https://github.com/mapzen/android/issues/196
https://github.com/mapzen/android/issues/197
https://github.com/mapzen/android/issues/198
