### ISSUE TITLE
Map does not render until gesture is detected

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#207]
### Description

Map tiles do not render until a gesture is detected (swipe, pinch, etc.)

### Steps to Reproduce

Open basic map SDK demo. Notice canvas is all gray. Swipe map and tiles start to load.

This only started to occur after updating the stylesheets for vector tiles 1.0.

### Mapzen SDK & Android Version

Mapzen SDK 1.1.1-SNAPSHOT (5784c046195d100f2f5e5b9df8eebc4af25524a0)
Android 6.0.1
Tangram 0.4.2

**Comment by tallytalwar** [comment]
Fixed via https://github.com/tangrams/tangram-es/pull/1007

**Comment by ecgreb** [comment]
Hmm ok this looks promising but that still raises a couple of questions..

1. I thought this bug was introduced after Tangram 0.4.2?
2. If this did exist in Tangram 0.4.2, why did it not manifest in SDK demo until we updated the stylesheets?
3. If this patch resolves the issue can we cut a bugfix release of Tangram for the vector tiles 1.0 release of the Android SDK?
