### ISSUE TITLE
Walkabout style markers and polylines

### ISSUE THREAD

**Issue by rwrx** [mapzen/android#216]
I have noticed that when switching to Walkabout style when there are on map some markers and polylines placed, they doesn't appear when using Walkabout style. All other styles are ok. I have also noticed that default marker and polyline styles are not defined in walkabout yaml style file. I suppose this is why it is happening.

**Comment by ecgreb** [comment]
This is correct.

@nvkelso are there plans to add the default Mapzen `mz_*` marker and polyline layers to Walkabout?

**Comment by ecgreb** [comment]
https://github.com/tangrams/walkabout-style/issues/93

**Comment by ecgreb** [comment]
All house stylesheets have now been updated to include default marker styles and will be available in the next release.

**Comment by rwrx** [comment]
Great! Also one offtopic question: when will be Tron 2.0 added to Mapzen Android SDK?

**Comment by ecgreb** [comment]
Fixed by https://github.com/mapzen/android/pull/288
