### ISSUE TITLE
2 seconds freezing when onResume

### ISSUE THREAD

**Issue by rwrx** [mapzen/android#222]
Hello, I have integrated Mapzen Android SDK alongside with Google Maps API into my app. I am mainly testing on Nexus 5 and Nexus 5X and I have noticed that always when activity with map goes to background (for example I will show another activity in my app) and then return to that activity map freezes for about 2 seconds which I think won't be good experience for users. Google Maps API for example doesn't have this lag. Do you know about this? Is it possible that this will be resolved in the future?

**Comment by blair1618** [comment]
Hello! I think that the delay you are seeing is the start-up time for tangram-es. We've noticed that for some scene files, tangram-es can take a long time to parse and load the scene. We're currently working on a solution to replace our current parsing code with something much faster: https://github.com/tangrams/tangram-es/issues/1004

**Comment by rwrx** [comment]
Thank you, great! But I am wondering why always when activity is brought back to foreground it needs to parse and load the scene. Isn't this useless (more importantly when it affects user experience with map)?

**Comment by blair1618** [comment]
Hmm that's a good point. The SDK does not re-create the tangram view each time an application is paused and resumed, so you shouldn't see that tangram start-up delay each time the app is resumed. 

Depending on your version of Android and available device memory, the OS may choose to kill your application when it is paused, which would mean that tangram *would* need to start up again each time you resume the app.

**Comment by rwrx** [comment]
Oh, no, I wasn't aware of this. I have called setStyle() basically every time when onResume is called for activity. But my code is more complicated so I didn't noticed it before. I am sorry. Thank you. Closing this issue.
