### ISSUE TITLE
Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.MapController.clearDataSource(long)' on a null object reference

### ISSUE THREAD

**Issue by rwrx** [mapzen/android#224]
Hello, one user had crash on my closed beta testing app reported through Crashlytics. I am attaching stack trace.
[com.vecturagames.android.app.gpxviewer.pro.beta_issue_19_error_581de724032f000128790d574b0e3621.txt](https://github.com/mapzen/android/files/613876/com.vecturagames.android.app.gpxviewer.pro.beta_issue_19_error_581de724032f000128790d574b0e3621.txt)

**Comment by blair1618** [comment]
This looks to me like the `MapData` that you are `clear()`ing has already been `remove()`d from the map. That can happen in two ways, either `remove()` was called directly on that `MapData`, or the `MapController` that created the `MapData` was destroyed. See https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapData.java#L51-L56

**Comment by rwrx** [comment]
Thank you for your answer. Unfortunately this happened on some of user's device and I don't have any repro steps. For now I don't have any `remove()` calls on any `MapData` instance in my code. I have only calls to all `MapzenMap` clearing methods for example `clearDroppedPins()`. So I'm guessing that it has something with clearing when app is destroyed. I'm calling this clearing in `onDestroy()` of map activity. It should be safe, shouldn't? Also this crash hasn't occurred on any of my testing devices.

**Comment by sarahlensing** [comment]
Can you upgrade to the latest version (1.4.0) and if this is still a problem, create a new issue? Thank you!
