### ISSUE TITLE
City names with french accents are misspelled when zoomed out

### ISSUE THREAD

**Issue by yanickv** [mapzen/android#233]
### Description
City names with french accents are misspelled when zoomed out

### Steps to Reproduce
Problem can be observed with city of Montreal in canada on Eraser Map app

![screenshot_20161220-212713](https://cloud.githubusercontent.com/assets/3969320/21375561/5969e4de-c6fc-11e6-84dc-b5162b4db2d2.png)

![screenshot_20161220-212733](https://cloud.githubusercontent.com/assets/3969320/21375563/5e27efca-c6fc-11e6-94b5-d343c07e00a2.png)

### Mapzen SDK & Android Version
SDK version 1.2.1 and Android 7.1.1

**Comment by matteblair** [comment]
Good catch.

This is reproducible in the JS renderer as well: http://tangrams.github.io/bubble-wrap/#7.41667/45.345/-73.086, which makes me think this is a problem with the underlying data or the way the scene file is interpreting it.

**Comment by sarahlensing** [comment]
This is no longer an issue when using the latest version of the Android SDK (1.4.0)
