### ISSUE TITLE
Reduce apk size

### ISSUE THREAD

**Issue by sleepnova** [mapzen/android#238]
### Description
Final apk size is too large. My app size was < 10MB. After including Mapzen SDK, it became 24MB. Which doubled my apk size. It would be nice if there is a way to reduce the size!

### Mapzen SDK & Android Version
1.2.1

**Comment by ecgreb** [comment]
Much of the size of the Mapzen Android SDK comes from the native rendering libraries that are compiled for multiple architectures. You can mitigate this issue by building multiple APKs and splitting by ABI.

https://developer.android.com/studio/build/configure-apk-splits.html
