### ISSUE TITLE
Toggle map overlays with global vars

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#244]
Implement convenience methods in the SDK to toggle map labels (none, some, more) and overlays (i.e. transit) using stylesheet global variables.

**Comment by sarahlensing** [comment]
Toggle only the overlays for this ticket.

Toggling labels currently requires switching scene files (which in most cases are spread across several repos). When support for themes is added, we can use this to toggle label variants. Relevant ticket for this work: https://github.com/mapzen/android/issues/372
