### ISSUE TITLE
[docs] Add LOST features to Android SDK docs

### ISSUE THREAD

**Issue by kkowalsky** [mapzen/android#248]
It's rather hard to find information about geofencing or other LOST services. We should add them to the documentation website to allow users to easily find them and have them be searchable.

**Comment by kkowalsky** [comment]
https://github.com/mapzen/lost/blob/master/docs/geofences.md in particular

**Comment by ecgreb** [comment]
Hi Katie yes this is (somewhat) by design. Geofences are still a relatively new feature in Lost and have not been well tested at this point.

Also we have future plans to better integrate them into the Mapzen SDK so for example a Geofence can be represented as a polygon on the map.
