### ISSUE TITLE
Single method to set SDK wide log level

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#266]
### Description

Currently log levels are configured individually per service (map, search, routing) and can be rather verbose. We should provide a single convenience method to turn debug logs on/off for all components.

### Steps to Reproduce

Use SDK and observe Android logcat.

### Mapzen SDK & Android Version

Mapzen SDK 1.2.1
Android 7.1.1

**Comment by sarahlensing** [comment]
Closing in favor of https://github.com/mapzen/android/issues/410
