### ISSUE TITLE
Add attribution to MapView & MapFragment?

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/android#28]
Currently we require "© Mapzen" in our terms but it seems like that is something we want to change. 

Open Questions: 

- What should this look like?
 - Expandable icon?
 - Text? "Mapzen" 
 - A logo?
 - Where does OSM have to be?
- Where should this link to?
 - mapzen.com/rights?

My proposal for v0 would be a small text link just saying "Mapzen" pointing to /rights. In a later version we could make something expandable. We update the legal docs to have something specific to mobile and say you should use our default implementation. 

CCing for thoughts: @nvkelso @bcamper @randymeech

**Comment by mjcunningham** [comment]
Let's make this a text link that says "Powered by Mapzen" and points to https://mapzen.com/rights/ for now.
