### ISSUE TITLE
Router is failing (403)

### ISSUE THREAD

**Issue by Nikituh** [mapzen/android#287]
### Description

Your Router example (in **samples_mapzen-android-sdk-sample**)  is constantly throwing 403.

### Steps to Reproduce

1. Clone the solution
2. Follow the necessary steps to get your project running
3. Run **samples_mapzen-android-sdk-sample**
4. Click on **Router**
5. Set two points
6. Press **Get Route**

-> Forbidden

### Mapzen SDK & Android Version

- Mapzen: Latest
- Android: 4.4

**Comment by ecgreb** [comment]
Hi @Nikituh one possibility is that the API key is not getting properly added to the request. Did you register for a Mapzen API key? Did you add it to the sample application as either a string resource or set it in code?

https://github.com/mapzen/android/blob/master/docs/getting-started.md

**Comment by Nikituh** [comment]
You're right, my bad. I was under the impression that the sample app would be able to work without any additional configuration. 

Closing.

**Comment by ecgreb** [comment]
Glad that did the trick.

We used to publish an "demo" API key with the sample app but it was getting used so much that everyone was getting rate limited so it's been working better to have everyone grab their own.

Let us know if you have any suggestions on how to improve the experience for getting up and running the first time :)
