### ISSUE TITLE
Update default attribution for Android SDK

### ISSUE THREAD

**Issue by nvkelso** [mapzen/android#289]
Picking up from https://github.com/pelias/pelias-android-sdk/issues/70#issuecomment-276683708...

Current default attribution in the SDK is a text link that appears in the bottom left corner of the map and reads "Powered by Mapzen". Clicking the text opens https://mapzen.com/rights in a browser.

Mapzen recently updated their attribution requirements at the https://mapzen.com/rights link to:

`© Mapzen, OpenStreetMap, and others`

HTML snippet:

```
© <a href="https://www.mapzen.com/rights">Mapzen</a>,  <a href="https://openstreetmap.org/copyright">OpenStreetMap</a>
, and <a href="https://www.mapzen.com/rights/#services-and-data-sources">others</a>.
```

I think it's reasonable to click thru to Mapzen.com/rights for now (versus separate link per HTML part as above. (Perhaps in the future this can get more sophisticated.)

![android sdk attribution](https://cloud.githubusercontent.com/assets/464123/22512506/400f5c26-e867-11e6-909b-43e10ab3def3.png)

**Comment by sarahlensing** [comment]
We decided to update the rights page to include mobile sections https://github.com/mapzen/ios/issues/257
