### ISSUE TITLE
Tron style still doesn't look correct

### ISSUE THREAD

**Issue by rwrx** [mapzen/android#330]
I have pulled newest version of Mapzen Android SDK to see whether Tron style is correct, but unfortunately it still looks as I mentioned in #206. I am attaching screenshots from Nexus 5X device with Android 7.1.1:

![tron-screen-01](https://cloud.githubusercontent.com/assets/2378743/23775065/0d80f6ac-0527-11e7-8fdf-daa4a56fbc2c.png)
![tron-screen-02](https://cloud.githubusercontent.com/assets/2378743/23775073/14f6f706-0527-11e7-8653-334b14bba2f1.png)
![tron-screen-03](https://cloud.githubusercontent.com/assets/2378743/23775070/1093b5be-0527-11e7-8ab6-b9ea1784ef7a.png)

**Comment by matteblair** [comment]
@rwrx Can you share the logcat output from your application when this happens (preferrably in a [gist](https://gist.github.com/) or [pastebin](http://pastebin.com/))?

**Comment by rwrx** [comment]
Ok, here it is: https://gist.github.com/rwrx/cc2ea81c5edcd15af66485e050349809

**Comment by matteblair** [comment]
The log seems to indicate that some of the GLSL code used in the style is missing, which would happen if the submodules in tron-style were not initialized.

Try `git submodule update --init --recursive` and rebuild.

**Comment by rwrx** [comment]
Thank you a lot. I always forgot about that --recursive option. I was doing only `git submodule update`. Thank you. Closing this.
