### ISSUE TITLE
Memory Leak in OverlayManager?

### ISSUE THREAD

**Issue by nebular** [mapzen/android#338]
I am debugging my app for memory leaks, as I'm getting some OOM's after I stop/restart the application a bunch of times.

I am using `LeakCanary` to track the leaks [https://medium.com/square-corner-blog/leakcanary-detect-all-memory-leaks-875ff8360745#.8fzmjudm6](LeakCanary).

It complains about `LocationFactory` keeping a reference to the `Context` (main activity), causing a leak of the whole activity and its fragments.

I have traced the issue down to the `OverlayManager` creating a LostApiClient in line #155, looks like it's for the MyLocationOverlay, even though I don't use it.

```
OverlayManager(MapView mapView, MapController mapController, MapDataManager mapDataManager,
      MapStateManager mapStateManager, LostApiClient lostApiClient) {
    if (lostApiClient == null) {
      lostApiClient = LocationFactory.sharedClient(mapView.getContext(), connectionCallbacks);
    }
 
```

Am I doing anything wrong that is causing this leak? Here's the trace from **LeakCanary**

```
03-20 22:20:02.558  8421 19229 D LeakCanary: * tv.nebular.conectabike.MainActivity has leaked:
03-20 22:20:02.558  8421 19229 D LeakCanary: * GC ROOT static com.mapzen.android.location.LocationFactory.context
03-20 22:20:02.558  8421 19229 D LeakCanary: * leaks tv.nebular.conectabike.MainActivity instance
03-20 22:20:02.558  8421 19229 D LeakCanary: * Retaining: 42 MB.
03-20 22:20:02.558  8421 19229 D LeakCanary: * Reference Key: a8d9245d-589f-4d73-944c-c5434eaddb61
03-20 22:20:02.558  8421 19229 D LeakCanary: * Device: samsung samsung GT-I9505 jgedlteue
03-20 22:20:02.558  8421 19229 D LeakCanary: * Android Version: 6.0.1 API: 23 LeakCanary: 1.5 00f37f5
03-20 22:20:02.558  8421 19229 D LeakCanary: * Durations: watch=316611ms, gc=292ms, heap dump=9873ms, analysis=39346ms
03-20 22:20:02.558  8421 19229 D LeakCanary: * Details:
03-20 22:20:02.558  8421 19229 D LeakCanary: * Class com.mapzen.android.location.LocationFactory
03-20 22:20:02.558  8421 19229 D LeakCanary: |   static $staticOverhead = byte[16]@315642689 (0x12d05341)
03-20 22:20:02.558  8421 19229 D LeakCanary: |   static shared = com.mapzen.android.lost.internal.LostApiClientImpl@317419328 (0x12eb6f40)
03-20 22:20:02.558  8421 19229 D LeakCanary: |   static context = tv.nebular.conectabike.MainActivity@316192512 (0x12d8b700)
03-20 22:20:02.558  8421 19229 D LeakCanary: * Instance of tv.nebular.conectabike.MainActivity

```

Thanks in advance !

**Comment by ecgreb** [comment]
@nebular thanks for the details report. It sounds like the activity is getting destroyed and recreated but the application is not. Not holding onto a reference to an Activity from a static field is one of the easiest ways to get a memory leak and we are guilty of that here.

https://github.com/mapzen/android/blob/master/core/src/main/java/com/mapzen/android/location/LocationFactory.java#L14

Perhaps we could get around this by using the application context when the shared location client is created rather than the activity context.

**Comment by nebular** [comment]
Using the application context will definitely work, as well as using a normal instance of LostClient instead of a Shared one, then clearing it in mapView.onDestroy(). I'd also suggest to create the LostClient only if / when the "LocationOverlay" is used.
