### ISSUE TITLE
Style Walkabout resets API_KEY

### ISSUE THREAD

**Issue by fokin33** [mapzen/android#341]
### Description
I add option menu to select map style. If i set Walkabout style i get in log:
D/OkHttp: java.io.IOException: Unexpected response code: Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://tile.mapzen.com/mapzen/vector/v1/all/12/2479/1281.topojson?api_key=&}
But if select other style it works correct.

### Steps to Reproduce
MapzenManager.instance(getApplicationContext()).setApiKey("mykey");

...
mMapView.getMapAsync(new OnMapReadyCallback()
                {
                    @Override
                    public void onMapReady(final MapzenMap mapzenMap)
                        {
                            mzmap=mapzenMap;
                            mapzenMap.setStyle(new BubbleWrapStyle());
...
public boolean onOptionsItemSelected(MenuItem item)
            {
                switch (item.getItemId())
                    {
                        case 5:
                            mzmap.setStyle(new WalkaboutStyle());

 
### Mapzen SDK & Android Version
compile 'com.mapzen:mapzen-android-sdk:1.3.2'
compile 'com.mapzen.tangram:tangram:0.5.1'
test on Android 5 and 7

**Comment by sarahlensing** [comment]
Fixed https://github.com/mapzen/android/issues/363
