### ISSUE TITLE
Modify marker position, icon, and size after creation

### ISSUE THREAD

**Issue by ecgreb** [mapzen/android#344]
After a maker is created using `MapzenMap#addMarker(MarkerOptions)` a developer should be able to modify the position, icon, size, and visibility of the `BitmapMarker` created.

**Comment by nebular** [comment]
As i see you are planning to add a lot of power to the markers, may I suggest to also add support for Drag and Drop? 

The only thing necessary would be to be able to capture the TouchUp event. Unfortunately at the moment if the `LongPressResponder` is called, there's not an equivalent of `SimpleTapUp`. If something like `LongPressTapUp` existed, the implementation from the developer side would be trivial.

**Comment by sarahlensing** [comment]
Created a ticket for supporting drag and drop with markers https://github.com/mapzen/android/issues/430
