### ISSUE TITLE
Walkabout style missing api key

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/android#363]
### Description
The api key is not properly appended to tile requests and we reach `MapController`'s L1122 IOException.

The sdk is on an old version of Walkabout (3.0.0 from Jan 19) and should probably be updated.

**Comment by sarahlensing** [comment]
This is still an issue with Walkabout 4.0.0.

I tried using older versions of tangram (back to 0.5.0) but still see this.

@tallytalwar do you have any idea what might be causing this? One thing I noticed is that we aren't resetting global variables when switching styles- could something about walkabout be different in the way it handles globals? I am using the style switcher demo in the android sdk to reproduce this (it loads walkabout 7.0.0 locally)

**Comment by tallytalwar** [comment]
Sure will check this out.
