### ISSUE TITLE
Update pelias to optional gid field

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/android#367]

**Comment by msmollin** [comment]
https://github.com/pelias/api/pull/884 for reference.

**Comment by sarahlensing** [comment]
Closing as there isn't any work to do, the `gid` field is an empty string by default so this upstream change will have no effect on our library

Reference:
https://github.com/pelias/pelias-android-sdk/blob/master/lib/src/main/java/com/mapzen/pelias/gson/Properties.java#L16
