### ISSUE TITLE
Override User-agent to enable tracking of Mobile-SDK usage

### ISSUE THREAD

**Issue by msmollin** [mapzen/android#382]
Per discussion that occurred here: https://github.com/mapzen/ios/issues/310 we should override the user agent to provide details for tracking.

The default user agent that NSURLSession default configuration sends up looks like `$(CFBundleName)/$(CFBundleVersion) CFNetwork/808.3 Darwin/16.3.0` which is pretty much useless for our case. 

What we want is something like
`User-Agent: <sdk_name>;<sdk_version>;<os_version>`

Thoughts on formatting @sarahlensing ?

**Comment by sarahlensing** [comment]
@msmollin The only thing I'd consider adding to the format is "service name" to allow for more granular stats without having to check other properties of the request. What do you think about updating the format to
```
User-Agent: <sdk_name>;<service_name>;<sdk_version>;<os_version>
```

**Comment by msmollin** [comment]
Eh we should be able to pull that data from the endpoint the user agent is coming through.
