### ISSUE TITLE
Support Multiple Map Instances

### ISSUE THREAD

**Issue by sarahlensing** [mapzen/android#436]
Tangram added support for multiple map instances with [this PR](https://github.com/tangrams/tangram-es/pull/1263), we should update the SDK to support them as well. This will require first testing the tangram code and then updating the SDK. We will need to figure out a way to map `MapView` objects to `OverlayManager` (and other singletons) across orientation changes.

**Comment by msmollin** [comment]
Investigate if rotation persistence would benefit from utilizing new android architecture components (i.e. ViewModel or something else)?
