### ISSUE TITLE
Multiple documentation places reference code that won't compile

### ISSUE THREAD

**Issue by msmollin** [mapzen/android#58]
In nearly all the documentation files, there's a line that looks like

`mapFragment = (MapFragment) getSupportFragmentManager().findFragmentById(R.id.fragment);`

This has line has multiple problems. `mapFragment` is never declared anywhere, and `R.id.fragment` does not match the the fragment's name when it's defined in https://github.com/mapzen/android/blob/master/docs/markers.md and is called `map_fragment`

The correct line should be `MapFragment mapFragment = (MapFragment) getSupportFragmentManager().findFragmentById(R.id.map_fragment);`

@ecgreb / @sarahlensing / @mjcunningham

**Comment by ecgreb** [comment]
Nice catch. The docs used to be correct :P Will update.
